
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Falls back to a dummy URL so `prisma generate` succeeds in CI/build environments
    // where DATABASE_URL is not available.  At runtime the real DATABASE_URL must be set.
    url: process.env.DATABASE_URL ?? "postgresql://ci:ci@localhost:5432/ci",
  },
});
